MVCProject/Controllers/PhonesController.cs
using MVCProject.Models;
using MVCProject.Models.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace MVCProject.Controllers
{
    [Authorize]
    public class PhonesController : Controller
    {
      private readonly GadgetDBContext db=new GadgetDBContext();
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult PhoneInfo(int page=1)
        {
            var data = db.Phones.Include(s => s.StockDetails).Include(s => s.PhoneModel).Include(s => s.Brand).OrderBy(s => s.PhoneId).ToPagedList(page, 5);
            return PartialView("_phoneInfo",data);
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateForm()
        {
            PhoneVM model = new PhoneVM();
            model.StockDetails.Add(new StockDetail());
            ViewBag.PhoneModel = db.PhoneModels.ToList();
            ViewBag.BrandModel = db.Brands.ToList();
            return PartialView("_CreateForm", model);
        }
        [HttpPost]
        public ActionResult Create(PhoneVM model , string cct="")
        {
            if (cct == "add")
            {
                model.StockDetails.Add(new StockDetail());
                foreach (var e in ModelState.Values) 
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (cct.StartsWith("remove"))
            {
                int index = int.Parse(cct.Substring(cct.IndexOf("_") + 1));
                model.StockDetails.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if(cct== "insert")
            {
                if(ModelState.IsValid)
                {
                    var phone = new Phone
                    {
                        BrandId = model.BrandId,
                        PhoneModelId = model.PhoneModelId,
                        PhoneName = model.PhoneName,
                        ReliseDate = model.ReliseDate,
                        IsOfficial = model.IsOfficial
                    };
                    //For Picture & File Path
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string ext2 = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Picture"), ext2);
                    model.Picture.SaveAs(savePath);
                    phone.Picture = ext2;
                    db.Phones.Add(phone);
                    db.SaveChanges();

                    foreach (var s in model.StockDetails) 
                    {
                        db.Database.ExecuteSqlCommand($"spInsertStock {(int)s.Color},{s.Price},{(int)s.Quantity},{phone.PhoneId}");
                    }
                    PhoneVM model2 = new PhoneVM()
                    {
                        PhoneName = "",
                        ReliseDate = DateTime.Today
                    };
                    model2.StockDetails.Add(new StockDetail());
                    ViewBag.PhoneModel = db.PhoneModels.ToList();
                    ViewBag.BrandModel=db.Brands.ToList();
                    foreach (var e in ModelState.Values)
                    {
                        e.Value = null;
                    }
                    return View("_CreateForm", model2);
                }
            }
            ViewBag.PhoneModel = db.PhoneModels.ToList();
            ViewBag.BrandModel = db.Brands.ToList();
            return View("_CreateForm", model);
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data = db.Phones.FirstOrDefault(x => x.PhoneId == id);
            if (data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x => x.StockDetails).Load();
            PhoneEditVM model = new PhoneEditVM()
            {
                PhoneId = id,
                BrandId = data.BrandId,
                PhoneModelId = data.PhoneModelId,
                PhoneName = data.PhoneName,
                ReliseDate = data.ReliseDate,
                IsOfficial = data.IsOfficial,
                StockDetails = data.StockDetails.ToList()
            };
            ViewBag.PhoneModel = db.PhoneModels.ToList();
            ViewBag.BrandModel = db.Brands.ToList();
            ViewBag.CurrentPic = data.Picture;
            return PartialView("_editForm", model);
        }
        [HttpPost]
        public ActionResult Edit(PhoneEditVM mo, string cct = "")
        {
            if (cct == "add")
            {
                mo.StockDetails.Add(new StockDetail());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (cct.StartsWith("remove"))
            {
                int index = int.Parse(cct.Substring(cct.IndexOf("_") + 1));
                mo.StockDetails.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (cct == "update")
            {
                if (ModelState.IsValid)
                {
                    var phone = db.Phones.FirstOrDefault(x => x.PhoneId == mo.PhoneId);
                    if (phone == null) { return new HttpNotFoundResult(); }
                    phone.PhoneName = mo.PhoneName;
                    phone.ReliseDate = mo.ReliseDate;
                    phone.IsOfficial = mo.IsOfficial;
                    phone.BrandId = mo.BrandId;
                    phone.PhoneModelId = mo.PhoneModelId;
                    if (mo.Picture != null)
                    {
                        string ext = Path.GetExtension(mo.Picture.FileName);
                        string ext2 = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Path.Combine(Server.MapPath("~/Picture"), ext2);
                        mo.Picture.SaveAs(savePath);
                        phone.Picture = ext2;
                    }
                    else
                    {

                    }

                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand($"EXEC spDeleteStock {phone.PhoneId}");
                    foreach (var s in mo.StockDetails)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC spInsertStock {(int)s.Color}, {s.Price}, {s.Quantity}, {phone.PhoneId}");
                    }
                }
            }
            ViewBag.PhoneModel = db.PhoneModels.ToList();
            ViewBag.BrandModel = db.Brands.ToList();
            ViewBag.CurrentPic = db.Phones.FirstOrDefault(x => x.PhoneId == mo.PhoneId)?.Picture;
            return View("_EditForm", mo);
        }
        public ActionResult Delete(int? id)
        {
            var phones = db.Phones.FirstOrDefault(x => x.PhoneId == id);
            if (phones != null)
            {
                var phnmdl = db.StockDetails.Where(x => x.PhoneId == id).ToList();
                db.StockDetails.RemoveRange(phnmdl);
                db.Phones.Remove(phones);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index");
        }
        
    }
}

MVCProject/Views/Phones/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row" style="background-color:steelblue">
    <div class="col">
        <div id="form-div">
            @Html.Action("CreateForm")
        </div>
    </div>
</div>

MVCProject/Views/Phones/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col">
        <div id="form-div">
            @Html.Action("EditForm")
        </div>
    </div>
</div>

MVCProject/Views/Phones/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="display-4" style="color:blueviolet">Phone List</h2>
<div class="row">
    <div class="col">
        <div class="d-flex justify-content-end">
            <a href="@Url.Action("Create","Phones")" class="btn btn-outline-primary btn-sm"><i class="fa fa-plus-circle"></i> Add New Phone</a>
        </div>
        <div id="table-div">
            @Html.Action("PhoneInfo")
        </div>
    </div>
</div>
@section styles{
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
}
@section scripts{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    <script>
        $(document).on("click", "button.show", function () {
            var showBtn = $(this);
            var hideBtn = showBtn.next();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.hide();
            hideBtn.show();
            trSt.show();
        });
        $(document).on("click", "button.hide", function () {
            var hideBtn = $(this);
            var showBtn = hideBtn.prev();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.show();
            hideBtn.hide();
            trSt.hide();
        });
    </script>
    }

MVCProject/Views/Phones/_CreateForm.cshtml
@model MVCProject.Models.ViewModels.PhoneVM
@using (Ajax.BeginForm("Create", "Phones", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div",
    OnSuccess = "Success"}, new { id = "frm", enctype = "multipart/form-data" }))
{
    <h3 class="display-4">Add New Phones</h3>
    <div class="row mb-2">
     @Html.LabelFor(x => x.BrandId, new { @class = "col-form-label col-2 " })
     <div class="col-6">
         @Html.DropDownListFor(x => x.BrandId, new SelectList(ViewBag.BrandModel, "BrandId", "BrandName"), "---Select---", new { @class = "form-select" })
     </div>
     <div class="col-4">
         @Html.ValidationMessageFor(x => x.BrandId, "", new { @class = "text-danger" })
     </div>
 </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.PhoneModelId, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.DropDownListFor(s => s.PhoneModelId, new SelectList(ViewBag.PhoneModel, "PhoneModelId", "ModelName"), "--Select Model--", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.PhoneModelId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.PhoneName, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.TextBoxFor(s => s.PhoneName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.PhoneName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.ReliseDate, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.TextBoxFor(s => s.ReliseDate, new { @class = "form-control", type = "date" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.ReliseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.Picture, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.TextBoxFor(s => s.Picture, new { @class = "form-control", type = "file" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.Picture, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-10 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(s=>s.IsOfficial)
                <label>
                    Is It Official Device?
                </label>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <div class="d-flex justify-content-between">
                <h2 class="display-4">Stock Details</h2>
                <button class="btn btn-outline-info btn-sm" type="submit" name="cct" value="add" formnovalidate><i class="fa fa-plus-circle"></i></button>
            </div>
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>Color :</th>
                        <th>Price :</th>
                        <th>Quantity :</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.StockDetails.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(s => Model.StockDetails[i].Color, new { @class = "form-select" })
                                @Html.ValidationMessageFor(s => Model.StockDetails[i].Color, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(s => Model.StockDetails[i].Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(s => Model.StockDetails[i].Price, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(s => Model.StockDetails[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(s => Model.StockDetails[i].Quantity, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="cct" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate><i class="fa fa-remove"></i></button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            <button type="submit" name="cct" value="insert" class="btn btn-outline-warning btn-lg"><i class="fa fa-save"></i>Save</button>
        </div>

    </div>
}

MVCProject/Views/Phones/_editForm.cshtml
@model MVCProject.Models.ViewModels.PhoneEditVM
@using (Ajax.BeginForm("Edit", "Phones", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div"}, new { id = "frm", enctype = "multipart/form-data" }))
{
    <h3 class="display-4" style="background-color:antiquewhite;">Edit Order</h3>
    <div class="row mb-2">
        @Html.HiddenFor(s => s.PhoneId)
        @Html.HiddenFor(s => s.Picture)
        @Html.LabelFor(s => s.BrandId, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.DropDownListFor(s => s.BrandId, new SelectList(ViewBag.BrandModel, "BrandId", "BrandName"), "--Select Brand--", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.BrandId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.PhoneModelId, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.DropDownListFor(s => s.PhoneModelId, new SelectList(ViewBag.PhoneModel, "PhoneModelId", "ModelName"), "--Select Model--", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.PhoneModelId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.PhoneName, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.TextBoxFor(s => s.PhoneName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.PhoneName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.ReliseDate, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.TextBoxFor(s => s.ReliseDate,"{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(s => s.ReliseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        @Html.LabelFor(s => s.Picture, new { @class = "col-form-label col-2" })
        <div class="col-6">
            @Html.TextBoxFor(s => s.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(s => s.Picture, "", new { @class = "text-danger" })
        </div>
        <div class="col-4">
            <img src="~/Picture/@ViewBag.CurrentPic" style="width:35px;" class="img-thumbnail" /> 
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-10 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(s => s.IsOfficial)
                <label>
                    Is It Official Device?
                </label>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <div class="d-flex justify-content-between">
                <h2 class="display-4">Stock Details</h2>
                <button class="btn btn-outline-info btn-sm" type="submit" name="cct" value="add" formnovalidate><i class="fa fa-plus-circle"></i></button>
            </div>
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>Color :</th>
                        <th>Price :</th>
                        <th>Quantity :</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.StockDetails.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(s => Model.StockDetails[i].Color, new { @class = "form-select" })
                                @Html.ValidationMessageFor(s => Model.StockDetails[i].Color, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(s => Model.StockDetails[i].Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(s => Model.StockDetails[i].Price, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(s => Model.StockDetails[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(s => Model.StockDetails[i].Quantity, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="cct" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate><i class="fa fa-remove"></i></button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            <button type="submit" name="cct" value="update" class="btn btn-outline-success btn-lg"><i class="fa fa-save"></i>Update</button>
        </div>

    </div>
}

MVCProject/Views/Phones/_phoneInfo.cshtml
@model IEnumerable<MVCProject.Models.Phone>

@using PagedList
@using PagedList.Mvc


<table class="table table-bordered table-striped table-sm mt-2">
    <thead class="table-primary">
        <tr>
            <th>Details</th>
            <th>Picture</th>
            <th>Brand</th>
            <th>Model</th>
            <th>Realise Date</th>
            <th>Is It Official?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td style="width:40px;text-align:center;">
                    <button type="button" class="btn btn-sm show"><i class="bi bi-chevron-right"></i></button>
                    <button type="button" class="btn btn-sm hide" style="display:none;"><i class="bi bi-chevron-up"></i></button>
                </td>
                <td style="width:45px;text-align:center">
                    <img src="~/Picture/@s.Picture" class="rounded-circle" style="width:32px;" />
                </td>
                <td>@s.Brand.BrandName</td>
                <td>@s.PhoneModel.ModelName</td>
                <td>@s.ReliseDate.ToString("yyyy-MM-dd")</td>
                <td>@(s.IsOfficial?"Yes":"No")</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Phones", new { id = s.PhoneId }, new { @class = "btn btn-outline-success btn-sm" })
                    @Html.ActionLink("Delete", "Delete", "Phones", new { id = s.PhoneId }, new { @class = "btn btn-outline-danger btn-sm" })
                </td>
            </tr>
            <tr style="display:none;">
                <td></td>
                <td colspan="6">
                    <h4>Stock Details</h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Color</th>
                                <th>Price</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var t in s.StockDetails)
                            {
                                <tr>
                                    <td>@t.Color</td>
                                    <td>@t.Price</td>
                                    <td>@t.Quantity</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }
    </tbody>
</table>